GET http://localhost:1000/systems
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE1MDViYzExMzFkOGExNjFhZDVkYzciLCJ1c2VybmFtZSI6IjM1MzA5QkQiLCJlbWFpbCI6IkRFVkBNQUlMLkNPTSIsImlhdCI6MTY3OTA5OTMyNH0.AswDYKXz-0GCgKn4-QF8hSbkmC0jIZoiZs2bhVfc3AY

###

POST http://localhost:1005/transact/swap
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE1MDViYzExMzFkOGExNjFhZDVkYzciLCJ1c2VybmFtZSI6IjM1MzA5QkQiLCJlbWFpbCI6IkRFVkBNQUlMLkNPTSIsImlhdCI6MTY3OTA5OTMyNH0.AswDYKXz-0GCgKn4-QF8hSbkmC0jIZoiZs2bhVfc3AY

{
    "from": "NGN" ,
    "to": "USD" ,
    "minOutput":1,
    "value":46024.89
}

####
POST http://localhost:2001/wallets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE1MDViYzExMzFkOGExNjFhZDVkYzciLCJ1c2VybmFtZSI6IjM1MzA5QkQiLCJlbWFpbCI6IkRFVkBNQUlMLkNPTSIsImlhdCI6MTY3OTA5OTMyNH0.AswDYKXz-0GCgKn4-QF8hSbkmC0jIZoiZs2bhVfc3AY
Content-Type: application/json

{
    "name":"Nigerian Naira",
    "symbol":"Ng",
    "code":"NGN"
}

###

POST http://localhost:1000/systems/get-transfer-methods
Content-Type: application/json

{
    "from":"USD",
    "to":"NGN" 
}

###
POST http://localhost:1000/systems/new-transfer-method
Content-Type: application/json

{
    "name":"Bank",
    "active":true,
    "description":"Use Bank payment method",
    "code":"BANK",
    "fee": 0,
    "wallets_for":["NGN", "UGX"]
}

###
POST http://localhost:1005/transact/send
Content-Type: application/json

{
    "method":"b",
    "destination":{
        "bank":"UBA",
        "account":"1234567890",
        "name":"Orjioke manfred tochukwu"
    },
    "currency":"NGN"
}