GET http://localhost:1000/systems
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE1MDViYzExMzFkOGExNjFhZDVkYzciLCJ1c2VybmFtZSI6IjM1MzA5QkQiLCJlbWFpbCI6IkRFVkBNQUlMLkNPTSIsImlhdCI6MTY3OTA5OTMyNH0.AswDYKXz-0GCgKn4-QF8hSbkmC0jIZoiZs2bhVfc3AY

###

POST http://localhost:1005/transact/swap
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE1MDViYzExMzFkOGExNjFhZDVkYzciLCJ1c2VybmFtZSI6IjM1MzA5QkQiLCJlbWFpbCI6IkRFVkBNQUlMLkNPTSIsImlhdCI6MTY3OTA5OTMyNH0.AswDYKXz-0GCgKn4-QF8hSbkmC0jIZoiZs2bhVfc3AY

{
    "from":{"code":"NGN"},
    "to":{"code":"USD"},
    "minOutput":1,
    "value":2
}

####
POST http://localhost:2001/wallets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE1MDViYzExMzFkOGExNjFhZDVkYzciLCJ1c2VybmFtZSI6IjM1MzA5QkQiLCJlbWFpbCI6IkRFVkBNQUlMLkNPTSIsImlhdCI6MTY3OTA5OTMyNH0.AswDYKXz-0GCgKn4-QF8hSbkmC0jIZoiZs2bhVfc3AY
Content-Type: application/json

{
    "name":"Nigerian Naira",
    "symbol":"Ng",
    "code":"NGN"
}

###

GET https://v6.exchangerate-api.com/v6/da8bb207555b91c52d1434ab/pair/NGN/USD/5040